### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FutureHackerHere** [lol-jude/Blooket-Hacks#117]
I can't get any of the boxes like wonderland and breakfast box

**Comment by possiblemonkeygamer** [comment]
dont type box. just type wonderland or medieval or breakfast

**Comment by lol-jude** [comment]
When it asks you type something like Space instead of Space Box, make sure its capital.

**Comment by glozygibbler** [comment]
type only the name. if it says how many thats where the problem is. you need to have coins/tokens in order to open them. or ex. if you have 100 coins/tokens and the box you want costs 20 coins/tokens, you can only spam 5 boxes. for every 1 box you want to spam open, is 1 second. if you have enough for 20 boxes, it takes 20 seconds to open all of them. hope this helps.
